# Generated by Django 6.0 on 2025-12-15 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.BigIntegerField(db_index=True)),
                ('end', models.BigIntegerField(db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
            options={
                'ordering': ['begin'],
                'indexes': [models.Index(fields=['begin', 'end'], name='app_phone_begin_c6a2d7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('begin__lte', models.F('end'))), name='phone_begin_lte_end')],
            },
        ),
    ]
